In [2]:
# read in HH income data by zip code, skip 1 row
# keep columns: zip code, HH mean income, HH median income
# extract numeric data from Geographic area name

In [3]:
import pandas as pd

In [4]:
# HH income data
HH_income_file_path = "/Users/mursil/workspace_neelam/Data_Projects_Personal/Real_Estate_Project/Household Income by Zip Code/ACSST5Y2021.S1901_2023-10-13T122844/ACSST5Y2021.S1901-Data.csv"

# # Read the csv file into DataFrame
HH_income = pd.read_csv(HH_income_file_path, skiprows=1)

In [5]:
HH_income.head()

,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,Annotation of Margin of Error!!Households!!Total,Annotation of Estimate!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Estimate!!Households!!Total!!Less than $10,000",...,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Unnamed: 258
0,0500000US32003,"Clark County, Nevada",816296,2377,NaN,NaN,6.4,0.2,NaN,NaN,...,(X),(X),(X),(X),(X),34.6,NaN,(X),(X),NaN
1,860Z200US84034,ZCTA5 84034,49,30,NaN,NaN,0.0,45.5,NaN,NaN,...,(X),(X),(X),(X),(X),45.5,NaN,(X),(X),NaN
2,860Z200US89001,ZCTA5 89001,510,128,NaN,NaN,0.0,7.5,NaN,NaN,...,(X),(X),(X),(X),(X),39.8,NaN,(X),(X),NaN
3,860Z200US89002,ZCTA5 89002,12737,641,NaN,NaN,2.9,1.4,NaN,NaN,...,(X),(X),(X),(X),(X),31.8,NaN,(X),(X),NaN
4,860Z200US89003,ZCTA5 89003,514,191,NaN,NaN,11.1,11.6,NaN,NaN,...,(X),(X),(X),(X),(X),15.2,NaN,(X),(X),NaN

In [6]:
HH_income = HH_income.drop(0, axis=0)

In [7]:
HH_income.head()

,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,Annotation of Margin of Error!!Households!!Total,Annotation of Estimate!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Estimate!!Households!!Total!!Less than $10,000",...,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Unnamed: 258
1,860Z200US84034,ZCTA5 84034,49,30,NaN,NaN,0.0,45.5,NaN,NaN,...,(X),(X),(X),(X),(X),45.5,NaN,(X),(X),NaN
2,860Z200US89001,ZCTA5 89001,510,128,NaN,NaN,0.0,7.5,NaN,NaN,...,(X),(X),(X),(X),(X),39.8,NaN,(X),(X),NaN
3,860Z200US89002,ZCTA5 89002,12737,641,NaN,NaN,2.9,1.4,NaN,NaN,...,(X),(X),(X),(X),(X),31.8,NaN,(X),(X),NaN
4,860Z200US89003,ZCTA5 89003,514,191,NaN,NaN,11.1,11.6,NaN,NaN,...,(X),(X),(X),(X),(X),15.2,NaN,(X),(X),NaN
5,860Z200US89004,ZCTA5 89004,110,57,NaN,NaN,0.0,29.6,NaN,NaN,...,(X),(X),(X),(X),(X),48.4,NaN,(X),(X),NaN

In [8]:
# Remove "ZCTA5 " from the 'Geographic Area Name' column and convert the result to numeric
HH_income['Geographic Area Name'] = HH_income['Geographic Area Name'].str.replace('ZCTA5 ', '').astype(int)

In [9]:
HH_income.head()

,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,Annotation of Margin of Error!!Households!!Total,Annotation of Estimate!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Estimate!!Households!!Total!!Less than $10,000",...,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Unnamed: 258
1,860Z200US84034,84034,49,30,NaN,NaN,0.0,45.5,NaN,NaN,...,(X),(X),(X),(X),(X),45.5,NaN,(X),(X),NaN
2,860Z200US89001,89001,510,128,NaN,NaN,0.0,7.5,NaN,NaN,...,(X),(X),(X),(X),(X),39.8,NaN,(X),(X),NaN
3,860Z200US89002,89002,12737,641,NaN,NaN,2.9,1.4,NaN,NaN,...,(X),(X),(X),(X),(X),31.8,NaN,(X),(X),NaN
4,860Z200US89003,89003,514,191,NaN,NaN,11.1,11.6,NaN,NaN,...,(X),(X),(X),(X),(X),15.2,NaN,(X),(X),NaN
5,860Z200US89004,89004,110,57,NaN,NaN,0.0,29.6,NaN,NaN,...,(X),(X),(X),(X),(X),48.4,NaN,(X),(X),NaN

In [10]:
HH_income = HH_income.rename(columns={'Geographic Area Name': 'Zip_Code', 'Estimate!!Households!!Median income (dollars)' : 'Median_Income', 'Margin of Error!!Households!!Median income (dollars)' : 'Median_Income_Margin_of_Error',  'Estimate!!Households!!Mean income (dollars)' : 'Mean_Income', 'Margin of Error!!Households!!Mean income (dollars)' : 'Mean_Income_Margin_of_Error'})

In [11]:
HH_income.head()

,Geography,Zip_Code,Estimate!!Households!!Total,Margin of Error!!Households!!Total,Annotation of Margin of Error!!Households!!Total,Annotation of Estimate!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Margin of Error!!Households!!Total!!Less than $10,000","Annotation of Estimate!!Households!!Total!!Less than $10,000",...,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Annotation of Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Unnamed: 258
1,860Z200US84034,84034,49,30,NaN,NaN,0.0,45.5,NaN,NaN,...,(X),(X),(X),(X),(X),45.5,NaN,(X),(X),NaN
2,860Z200US89001,89001,510,128,NaN,NaN,0.0,7.5,NaN,NaN,...,(X),(X),(X),(X),(X),39.8,NaN,(X),(X),NaN
3,860Z200US89002,89002,12737,641,NaN,NaN,2.9,1.4,NaN,NaN,...,(X),(X),(X),(X),(X),31.8,NaN,(X),(X),NaN
4,860Z200US89003,89003,514,191,NaN,NaN,11.1,11.6,NaN,NaN,...,(X),(X),(X),(X),(X),15.2,NaN,(X),(X),NaN
5,860Z200US89004,89004,110,57,NaN,NaN,0.0,29.6,NaN,NaN,...,(X),(X),(X),(X),(X),48.4,NaN,(X),(X),NaN

In [12]:
HH_income = HH_income[['Zip_Code', 'Median_Income','Median_Income_Margin_of_Error', 'Mean_Income', 'Mean_Income_Margin_of_Error']]

In [13]:
HH_income.head()

,Zip_Code,Median_Income,Median_Income_Margin_of_Error,Mean_Income,Mean_Income_Margin_of_Error
1,84034,53750,39181,61392,27023
2,89001,75612,29846,86815,24185
3,89002,88425,5509,106159,5227
4,89003,-,**,44169,17697
5,89004,66328,20632,78475,23136

In [15]:
HH_income.to_csv("HH_income.csv", index = False)