In [ ]:
# Task description:
# Join multiple csv files and an excel file. 
# Performance data by school (high school ELA and math, elementary ELA, math and science)
# A list of schools and their addresses, including zip code
# the School ID is the join key.

In [ ]:
# Goal: Aggregate all the performance data into one dataframe
# Columns: School_name | School_id | ELA_percent_proficient | Math_percent_proficient | Science_percent_proficient
# Name of this dataframe School_perf_aggregated

In [2]:
# Goal: Join school_perf_aggregated with school_address based on school_id (Goal is to extract zip code)
# New columns: zip code
# Join key is school_id. There is a leading zero in [dataset]
# Name of this dataframe: School_performance_and_zip_code

In [5]:
# Import libraries [pandas]
import pandas as pd

In [6]:
# School Performance Data
ELA_Math_Elementary_file_path = "/Users/mursil/workspace_neelam/Data_Projects_Personal/Real_Estate_Project/School Performance Information/ELA_Math_Elementary_by_School_2022_2023.csv"
ELA_Math_High_School_file_path = "/Users/mursil/workspace_neelam/Data_Projects_Personal/Real_Estate_Project/School Performance Information/ELA_Math_High_School_by_school_2022_2023.csv"
Science_Elementary_file_path = "/Users/mursil/workspace_neelam/Data_Projects_Personal/Real_Estate_Project/School Performance Information/Science_Elementary_by_School_2022_2023.csv"

# # Read the csv files into DataFrames
ELA_Math_Elementary = pd.read_csv(ELA_Math_Elementary_file_path, skiprows=3)
ELA_Math_High_School = pd.read_csv(ELA_Math_High_School_file_path, skiprows=3)
Science_Elementary = pd.read_csv(Science_Elementary_file_path, skiprows=3)

In [7]:
ELA_Math_Elementary.columns

Index(['Group', 'Organization Code', 'Year', '# Eligible for CRT (ELA/Math)',
       'Mathematics - Number Tested', 'Mathematics - % Not Tested',
       'Mathematics - % Tested', 'Mathematics - % Proficient',
       'Mathematics - % Emergent/Developing',
       'Mathematics - % Approaches Standard', 'Mathematics - % Meets Standard',
       'Mathematics - % Exceeds Standard', 'ELA - Number Tested',
       'ELA - % Not Tested', 'Reading - % Tested', 'ELA - % Proficient',
       'ELA - % Emergent/Developing', 'ELA - % Approaches Standard',
       'ELA - % Meets Standard', 'ELA - % Exceeds Standard'],
      dtype='object')

In [8]:
ELA_Math_High_School.columns

Index(['Group', 'Organization Code', 'Year', '# Eligible for CCR (ELA/Math)',
       'Mathematics - Number Tested', 'Mathematics - % Not Tested',
       'Mathematics - % Tested', 'Mathematics - % Proficient',
       'Mathematics - % Emergent/Developing',
       'Mathematics - % Approaches Standard', 'Mathematics - % Meets Standard',
       'Mathematics - % Exceeds Standard', 'ELA - Number Tested',
       'ELA - % Not Tested', 'English - % Tested', 'ELA - % Proficient',
       'ELA - % Emergent/Developing', 'ELA - % Approaches Standard',
       'ELA - % Meets Standard', 'ELA - % Exceeds Standard'],
      dtype='object')

In [9]:
Science_Elementary.columns

Index(['Group', 'Organization Code', 'Year', '# Eligible for CRT (Science)',
       'Science - Number Tested', 'Science - % Not Tested',
       'Science - % Tested', 'Science - % Proficient',
       'Science - % Emergent/Developing', 'Science - % Approaches Standard',
       'Science - % Meets Standard', 'Science - % Exceeds Standard'],
      dtype='object')

In [10]:
Science_Elementary.info

<bound method DataFrame.info of                                      Group  Organization Code       Year  \
0                                    Clark                  2  2022-2023
1                100 Academy of Excellence               2364  2022-2023
2             100 Academy of Excellence ES               2093  2022-2023
3                      Abston, Sandra B ES               2061  2022-2023
4    Addeliar D. Guy III Elementary School               2161  2022-2023
..                                     ...                ...        ...
306     William K. Moore Elementary School               2282  2022-2023
307    William R. Lummis Elementary School               2141  2022-2023
308    William V. Wright Elementary School               2200  2022-2023
309  Wing and Lilly Fong Elementary School               2119  2022-2023
310  Zel and Mary Lowman Elementary School               2144  2022-2023

    # Eligible for CRT (Science) Science - Number Tested  \
0                          45580                   44470
1                             22                      21
2                             39                      39
3                            116                     116
4                             65                      65
..                           ...                     ...
306                           91                      90
307                           79                      79
308                           90                      90
309                          103                     102
310                          111                     111

    Science - % Not Tested Science - % Tested Science - % Proficient  \
0                       <5                >95                   23.0
1                       <5                >95                      -
2                       <5                >95                      -
3                       <5                >95                   22.4
4                       <5                >95                      -
..                     ...                ...                    ...
306                     <5                >95                      -
307                     <5                >95                   24.1
308                     <5                >95                   15.6
309                     <5                >95                   13.7
310                     <5                >95                      -

    Science - % Emergent/Developing Science - % Approaches Standard  \
0                              44.7                            32.3
1                                 -                               -
2                              64.1                            30.8
3                              37.9                            39.7
4                              58.5                            27.7
..                              ...                             ...
306                            66.7                            25.6
307                            27.8                            48.1
308                            32.2                            52.2
309                            48.0                            38.2
310                            73.9                            25.2

    Science - % Meets Standard Science - % Exceeds Standard
0                         19.0                           <5
1                            -                            -
2                            -                            -
3                         20.7                            -
4                            -                            -
..                         ...                          ...
306                          -                            -
307                       22.8                            -
308                       14.4                            -
309                       12.7                            -
310                          -                            -

[311 rows x 12 columns]>

In [11]:
ELA_Math_Elementary.info

<bound method DataFrame.info of                                      Group  Organization Code       Year  \
0                                    Clark                  2  2022-2023
1                100 Academy of Excellence               2364  2022-2023
2             100 Academy of Excellence ES               2093  2022-2023
3                      Abston, Sandra B ES               2061  2022-2023
4    Addeliar D. Guy III Elementary School               2161  2022-2023
..                                     ...                ...        ...
309     William K. Moore Elementary School               2282  2022-2023
310    William R. Lummis Elementary School               2141  2022-2023
311    William V. Wright Elementary School               2200  2022-2023
312  Wing and Lilly Fong Elementary School               2119  2022-2023
313  Zel and Mary Lowman Elementary School               2144  2022-2023

    # Eligible for CRT (ELA/Math) Mathematics - Number Tested  \
0                          133035                      129783
1                              85                          84
2                             124                         121
3                             346                         345
4                             218                         218
..                            ...                         ...
309                           279                         279
310                           234                         231
311                           279                         276
312                           299                         298
313                           324                         323

    Mathematics - % Not Tested Mathematics - % Tested  \
0                           <5                    >95
1                           <5                    >95
2                           <5                    >95
3                           <5                    >95
4                           <5                    >95
..                         ...                    ...
309                         <5                    >95
310                         <5                    >95
311                         <5                    >95
312                         <5                    >95
313                         <5                    >95

    Mathematics - % Proficient Mathematics - % Emergent/Developing  \
0                         28.2                                47.6
1                            -                                73.8
2                          9.9                                62.8
3                         40.3                                36.5
4                         22.9                                50.9
..                         ...                                 ...
309                       17.9                                60.6
310                       55.0                                22.5
311                       51.8                                25.7
312                       28.9                                47.0
313                        7.4                                72.4

    Mathematics - % Approaches Standard Mathematics - % Meets Standard  \
0                                  24.2                           16.1
1                                  19.0                              -
2                                  27.3                            9.1
3                                  23.2                           23.2
4                                  26.1                           16.5
..                                  ...                            ...
309                                21.5                           10.0
310                                22.5                           25.5
311                                22.5                           25.0
312                                24.2                           20.5
313                                20.1                            5.6

    Mathematics - % Exceeds Standard ELA - Number Tested ELA - % Not Tested  \
0                               12.1              130094                 <5
1                                  -                  85                 <5
2                                  -                 124                 <5
3                               17.1                 345                 <5
4                                6.4                 218                 <5
..                               ...                 ...                ...
309                              7.9                 279                 <5
310                             29.4                 233                 <5
311                             26.8                 277                 <5
312                              8.4                 297                 <5
313                                -                 323                 <5

    Reading - % Tested ELA - % Proficient ELA - % Emergent/Developing  \
0                  >95               39.0                        37.6
1                  >95               23.5                        47.1
2                  >95               17.7                        63.7
3                  >95               47.0                        27.2
4                  >95               28.4                        50.5
..                 ...                ...                         ...
309                >95               25.1                        54.8
310                >95               62.7                        15.5
311                >95               54.5                        27.1
312                >95               31.6                        48.5
313                >95               13.0                        70.6

    ELA - % Approaches Standard ELA - % Meets Standard  \
0                          23.4                   24.4
1                          29.4                   22.4
2                          18.5                   13.7
3                          25.8                   28.4
4                          21.1                   18.8
..                          ...                    ...
309                        20.1                   15.4
310                        21.9                   28.3
311                        18.4                   24.2
312                        19.9                   20.2
313                        16.4                    8.7

    ELA - % Exceeds Standard
0                       14.6
1                          -
2                          -
3                       18.6
4                        9.6
..                       ...
309                      9.7
310                     34.3
311                     30.3
312                     11.4
313                       <5

[314 rows x 20 columns]>

In [12]:
ELA_Math_High_School.info

<bound method DataFrame.info of                                                Group  Organization Code  \
0                                              Clark                  2
1                               Acceleration Academy               2716
2                      Advanced Technologies Academy               2420
3                             Arbor View High School               2618
4                                  Basic High School               2406
..                                               ...                ...
66     Veterans Tribute Career and Technical Academy               2432
67                         Virgin Valley High School               2603
68                 West Career and Technical Academy               2435
69  West Preparatory Academy at Charles I. West Hall               2330
70                               Western High School               2405

         Year # Eligible for CCR (ELA/Math) Mathematics - Number Tested  \
0   2022-2023                         24579                       22606
1   2022-2023                           368                          19
2   2022-2023                           266                         266
3   2022-2023                           810                         786
4   2022-2023                           591                         558
..        ...                           ...                         ...
66  2022-2023                           182                         179
67  2022-2023                           198                         196
68  2022-2023                           362                         358
69  2022-2023                            83                          82
70  2022-2023                           641                         584

   Mathematics - % Not Tested Mathematics - % Tested  \
0                         8.0                   92.0
1                        94.8                    5.2
2                          <5                    >95
3                          <5                    >95
4                         5.6                   94.4
..                        ...                    ...
66                         <5                    >95
67                         <5                    >95
68                         <5                    >95
69                         <5                    >95
70                        8.9                   91.1

   Mathematics - % Proficient Mathematics - % Emergent/Developing  \
0                        19.2                                34.3
1                           -                                52.6
2                        71.8                                   -
3                        20.7                                28.1
4                         9.3                                42.5
..                        ...                                 ...
66                       28.5                                11.7
67                       19.9                                26.0
68                       57.5                                 5.6
69                       18.3                                28.0
70                         <5                                55.7

   Mathematics - % Approaches Standard Mathematics - % Meets Standard  \
0                                 46.6                           12.8
1                                    -                              -
2                                 26.3                           33.8
3                                 51.1                           12.2
4                                 48.2                            8.2
..                                 ...                            ...
66                                59.8                           21.2
67                                54.1                           14.8
68                                36.9                           29.1
69                                53.7                           12.2
70                                40.9                             <5

   Mathematics - % Exceeds Standard ELA - Number Tested ELA - % Not Tested  \
0                               6.3               22111               10.0
1                                 -                  19               94.8
2                              38.0                 265                 <5
3                               8.5                 779                 <5
4                                 -                 531               10.2
..                              ...                 ...                ...
66                              7.3                 179                 <5
67                              5.1                 193                 <5
68                             28.5                 357                 <5
69                                -                  79                 <5
70                                -                 552               13.9

   English - % Tested ELA - % Proficient ELA - % Emergent/Developing  \
0                90.0               45.9                        20.6
1                 5.2                  -                           -
2                 >95               91.3                           -
3                 >95               48.7                        13.0
4                89.8               36.9                        25.4
..                ...                ...                         ...
66                >95               67.6                           -
67                >95               41.5                        18.1
68                >95               89.6                           -
69                >95               34.2                        24.1
70               86.1               14.9                        46.7

   ELA - % Approaches Standard ELA - % Meets Standard ELA - % Exceeds Standard
0                         33.6                   33.4                     12.5
1                            -                      -                        -
2                          8.3                   37.0                     54.3
3                         38.4                   36.6                     12.1
4                         37.7                   27.1                      9.8
..                         ...                    ...                      ...
66                        27.4                   50.8                     16.8
67                        40.4                   36.3                      5.2
68                         9.8                   48.2                     41.5
69                        41.8                   27.8                        -
70                        38.4                   14.5                        -

[71 rows x 20 columns]>

In [13]:
Science_Elementary.columns

Index(['Group', 'Organization Code', 'Year', '# Eligible for CRT (Science)',
       'Science - Number Tested', 'Science - % Not Tested',
       'Science - % Tested', 'Science - % Proficient',
       'Science - % Emergent/Developing', 'Science - % Approaches Standard',
       'Science - % Meets Standard', 'Science - % Exceeds Standard'],
      dtype='object')

In [14]:
# Create a new dataframe for all schools with the following columns
# Decided to forego including science info, since it's only avail for elementary schools and ELA and math will provide enough info
# ['Group', 'Organization Code', 'Mathematics - % Proficient','ELA - % Proficient']
# new dataframe is called ELA_Math_all
# no need to use a join key -- just need to pull in the appropriate columns

In [15]:
# Join the two datasets, ELA_Math_Elementary and ELA_Math_High_School

# List of DataFrames
df = [ELA_Math_Elementary, ELA_Math_High_School]

# Concatenate DataFrames vertically
ELA_Math_all = pd.concat(df, axis=0, ignore_index=True)

# Print the combined DataFrame
ELA_Math_all.head()

,Group,Organization Code,Year,# Eligible for CRT (ELA/Math),Mathematics - Number Tested,Mathematics - % Not Tested,Mathematics - % Tested,Mathematics - % Proficient,Mathematics - % Emergent/Developing,Mathematics - % Approaches Standard,...,ELA - Number Tested,ELA - % Not Tested,Reading - % Tested,ELA - % Proficient,ELA - % Emergent/Developing,ELA - % Approaches Standard,ELA - % Meets Standard,ELA - % Exceeds Standard,# Eligible for CCR (ELA/Math),English - % Tested
0,Clark,2,2022-2023,133035,129783,<5,>95,28.2,47.6,24.2,...,130094,<5,>95,39.0,37.6,23.4,24.4,14.6,NaN,NaN
1,100 Academy of Excellence,2364,2022-2023,85,84,<5,>95,-,73.8,19.0,...,85,<5,>95,23.5,47.1,29.4,22.4,-,NaN,NaN
2,100 Academy of Excellence ES,2093,2022-2023,124,121,<5,>95,9.9,62.8,27.3,...,124,<5,>95,17.7,63.7,18.5,13.7,-,NaN,NaN
3,"Abston, Sandra B ES",2061,2022-2023,346,345,<5,>95,40.3,36.5,23.2,...,345,<5,>95,47.0,27.2,25.8,28.4,18.6,NaN,NaN
4,Addeliar D. Guy III Elementary School,2161,2022-2023,218,218,<5,>95,22.9,50.9,26.1,...,218,<5,>95,28.4,50.5,21.1,18.8,9.6,NaN,NaN

In [16]:
ELA_Math_all.info

<bound method DataFrame.info of                                                 Group  Organization Code  \
0                                               Clark                  2
1                           100 Academy of Excellence               2364
2                        100 Academy of Excellence ES               2093
3                                 Abston, Sandra B ES               2061
4               Addeliar D. Guy III Elementary School               2161
..                                                ...                ...
380     Veterans Tribute Career and Technical Academy               2432
381                         Virgin Valley High School               2603
382                 West Career and Technical Academy               2435
383  West Preparatory Academy at Charles I. West Hall               2330
384                               Western High School               2405

          Year # Eligible for CRT (ELA/Math) Mathematics - Number Tested  \
0    2022-2023                        133035                      129783
1    2022-2023                            85                          84
2    2022-2023                           124                         121
3    2022-2023                           346                         345
4    2022-2023                           218                         218
..         ...                           ...                         ...
380  2022-2023                           NaN                         179
381  2022-2023                           NaN                         196
382  2022-2023                           NaN                         358
383  2022-2023                           NaN                          82
384  2022-2023                           NaN                         584

    Mathematics - % Not Tested Mathematics - % Tested  \
0                           <5                    >95
1                           <5                    >95
2                           <5                    >95
3                           <5                    >95
4                           <5                    >95
..                         ...                    ...
380                         <5                    >95
381                         <5                    >95
382                         <5                    >95
383                         <5                    >95
384                        8.9                   91.1

    Mathematics - % Proficient Mathematics - % Emergent/Developing  \
0                         28.2                                47.6
1                            -                                73.8
2                          9.9                                62.8
3                         40.3                                36.5
4                         22.9                                50.9
..                         ...                                 ...
380                       28.5                                11.7
381                       19.9                                26.0
382                       57.5                                 5.6
383                       18.3                                28.0
384                         <5                                55.7

    Mathematics - % Approaches Standard  ... ELA - Number Tested  \
0                                  24.2  ...              130094
1                                  19.0  ...                  85
2                                  27.3  ...                 124
3                                  23.2  ...                 345
4                                  26.1  ...                 218
..                                  ...  ...                 ...
380                                59.8  ...                 179
381                                54.1  ...                 193
382                                36.9  ...                 357
383                                53.7  ...                  79
384                                40.9  ...                 552

    ELA - % Not Tested Reading - % Tested ELA - % Proficient  \
0                   <5                >95               39.0
1                   <5                >95               23.5
2                   <5                >95               17.7
3                   <5                >95               47.0
4                   <5                >95               28.4
..                 ...                ...                ...
380                 <5                NaN               67.6
381                 <5                NaN               41.5
382                 <5                NaN               89.6
383                 <5                NaN               34.2
384               13.9                NaN               14.9

    ELA - % Emergent/Developing ELA - % Approaches Standard  \
0                          37.6                        23.4
1                          47.1                        29.4
2                          63.7                        18.5
3                          27.2                        25.8
4                          50.5                        21.1
..                          ...                         ...
380                           -                        27.4
381                        18.1                        40.4
382                           -                         9.8
383                        24.1                        41.8
384                        46.7                        38.4

    ELA - % Meets Standard ELA - % Exceeds Standard  \
0                     24.4                     14.6
1                     22.4                        -
2                     13.7                        -
3                     28.4                     18.6
4                     18.8                      9.6
..                     ...                      ...
380                   50.8                     16.8
381                   36.3                      5.2
382                   48.2                     41.5
383                   27.8                        -
384                   14.5                        -

    # Eligible for CCR (ELA/Math) English - % Tested
0                             NaN                NaN
1                             NaN                NaN
2                             NaN                NaN
3                             NaN                NaN
4                             NaN                NaN
..                            ...                ...
380                           182                >95
381                           198                >95
382                           362                >95
383                            83                >95
384                           641               86.1

[385 rows x 22 columns]>

In [17]:
# Keep only the columns: ['Group', 'Organization Code', 'Mathematics - % Proficient','ELA - % Proficient']

ELA_Math_all = ELA_Math_all[['Group', 'Organization Code', 'Mathematics - % Proficient','ELA - % Proficient']]

In [18]:
ELA_Math_all

,Group,Organization Code,Mathematics - % Proficient,ELA - % Proficient
0,Clark,2,28.2,39.0
1,100 Academy of Excellence,2364,-,23.5
2,100 Academy of Excellence ES,2093,9.9,17.7
3,"Abston, Sandra B ES",2061,40.3,47.0
4,Addeliar D. Guy III Elementary School,2161,22.9,28.4
...,...,...,...,...
380,Veterans Tribute Career and Technical Academy,2432,28.5,67.6
381,Virgin Valley High School,2603,19.9,41.5
382,West Career and Technical Academy,2435,57.5,89.6
383,West Preparatory Academy at Charles I. West Hall,2330,18.3,34.2
384,Western High School,2405,<5,14.9

In [19]:
# Bring in zip code data.
# Read in Website_SchoolList

School_List_file_path = "/Users/mursil/workspace_neelam/Data_Projects_Personal/Real_Estate_Project/School Performance Information/Website_SchoolList.xlsx"

# # Load the excel file into a DataFrame
School_List = pd.read_excel(School_List_file_path)

In [20]:
School_List.head(50)

,SchoolYear,District Code,District Name,School Code,ACT Code,School Name,School Abbreviation,School Type,Mailing Address,Mailing City,...,Virtual,Title I,Low Grade,High Grade,Acct Low Grade Level 1,Acct High Grade Level 1,Acct Low Grade Level 2,Acct High Grade Level 2,Acct Low Grade Level 3,Acct High Grade Level 3
0,2223,1,Churchill,1202,--,Northside Early Learning Center,Northside Early Learning,RG,340 Venturacci Ln,Fallon,...,N,Y,PK,PK,--,--,--,--,--,--
1,2223,1,Churchill,1205,--,E C Best Elementary,Best ES,RG,750 E Williams Ave,Fallon,...,N,Y,02,03,02,03,--,--,--,--
2,2223,1,Churchill,1206,--,Lahontan Elementary School,Lahontan ES,RG,1099 Merton Drive,Fallon,...,N,Y,KG,01,KG,01,--,--,--,--
3,2223,1,Churchill,1207,--,Numa Elementary School,Numa ES,RG,601 Discovery Way,Fallon,...,N,Y,04,05,04,05,--,--,--,--
4,2223,1,Churchill,1301,--,Churchill County Middle School,Churchill MS,RG,650 South Maine Street,Fallon,...,N,Y,06,08,--,--,06,08,--,--
5,2223,1,Churchill,1401,290060,Churchill County High School,Churchill HS,RG,1 Greenwave Circle,Fallon,...,N,N,09,12,--,--,--,--,09,12
6,2223,1,Churchill,1902,--,Churchill County Adult Ed,Churchill Adult Ed,AD,280 South Russell Street,Fallon,...,N,N,AD,AD,--,--,--,--,--,--
7,2223,2,Clark County,2060,--,"Thompson, Tyrone ES",Thompson T ES,RG,10250 S. El Capitan Way,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
8,2223,2,Clark County,2061,--,"Abston, Sandra B ES",Abston ES,RG,9950 W Tompkins Ave,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
9,2223,2,Clark County,2062,--,"Jenkins, Earl N ES",Jenkins ES,RG,6950 Vegas Valley Dr,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
10,2223,2,Clark County,2064,--,"Ellis, Robert & Sandy ES",Ellis ES,RG,3200 Artella Avenue,Henderson,...,N,N,PK,05,KG,05,--,--,--,--
11,2223,2,Clark County,2065,--,"Ortwein, Dennis ES",Ortwein ES,RG,10926 Dean Martin Drive,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
12,2223,2,Clark County,2066,--,"Barber, Shirley A ES",Barber ES,RG,2002 Dave Street,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
13,2223,2,Clark County,2067,--,"Divich, Kenneth ES",Divich ES,RG,9851 Donald Nelson Ave,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
14,2223,2,Clark County,2068,--,"Jones Blackhurst, Jan L ES",Jones Blackhurst ES,RG,11141 S Pioneer Wy,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
15,2223,2,Clark County,2069,--,"Vassiliadis, Billy & Rosemary ES",Vassiliadis ES,RG,215 Antelope Ridge Dr,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
16,2223,2,Clark County,2070,--,"Berkley, Shelley ES",Berkley ES,RG,9850 Copper Edge Rd,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
17,2223,2,Clark County,2071,--,"Stevens, Josh ES",Stevens ES,RG,550 Dave Wood Circle,Henderson,...,N,Y,PK,05,KG,05,--,--,--,--
18,2223,2,Clark County,2072,--,"Mathis, Dr. Beverly S ES",Mathis ES,RG,7950 Arville St,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
19,2223,2,Clark County,2073,--,"Heard, Lomie G ES",Heard ES,RG,4497 Kell Ln,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
20,2223,2,Clark County,2074,--,"Snyder, Don & Dee ES",Snyder D ES,RG,8951 W Ford Ave,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
21,2223,2,Clark County,2075,--,NW Career-Technical Academy ES,NWCTA ES,RG,8200 W Tropical Pkwy,Las Vegas,...,N,N,KG,KG,KG,--,--,--,--,--
22,2223,2,Clark County,2076,--,"Duncan, Ruby ES",Duncan ES,RG,250 W Rome Blvd,N Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
23,2223,2,Clark County,2077,--,"Wallin, Shirley & Bill ES",Wallin ES,RG,2333 Canyon Retreat Dr,Henderson,...,N,N,PK,05,KG,05,--,--,--,--
24,2223,2,Clark County,2078,--,"Stuckey, Evelyn ES",Stuckey ES,RG,4905 Chartan Ave,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
25,2223,2,Clark County,2079,--,"Keller, Charlotte & Jerry ES",Keller ES,RG,5445 Cedar Ave,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
26,2223,2,Clark County,2080,--,"Fine, Mark L ES",Fine ES,RG,6635 W Cougar Ave,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
27,2223,2,Clark County,2081,--,"Bozarth, Henry & Evelyn ES",Bozarth ES,RG,7431 Egan Crest Dr,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
28,2223,2,Clark County,2082,--,"Triggs, Vincent L ES",Triggs ES,RG,4470 W Rome Blvd,N Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
29,2223,2,Clark County,2083,--,"O Roarke, Thomas ES",ORoarke ES,RG,8455 O'Hare Road,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
30,2223,2,Clark County,2084,--,"Reedom, Carolyn S ES",Reedom ES,RG,10025 Rumrill St,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
31,2223,2,Clark County,2085,--,"Diaz, Ruben P ES",Diaz ES,RG,4450 E Owens Ave,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
32,2223,2,Clark County,2086,--,"Scott, Jesse D ES",Scott ES,RG,5700 N Bruce St,N Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
33,2223,2,Clark County,2087,--,Rainbow Dreams Early Learning Academy,Rainbow Dreams ELA,DCH,950 W Lake Mead Blvd,Las Vegas,...,N,Y,PK,KG,KG,05,--,--,--,--
34,2223,2,Clark County,2088,--,Southeast Career Technical Academy PK,SECTA PK,EL,5710 Mountain Vista St.,Las Vegas,...,N,N,PK,PK,--,--,--,--,--,--
35,2223,2,Clark County,2089,--,West Prep ES,West Prep ES,RG,1950 Pink Rose St.,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
36,2223,2,Clark County,2090,--,"Smalley, James E & A Rae ES",Smalley,RG,304 E Paradise Hills Dr,Henderson,...,N,N,PK,05,KG,05,--,--,--,--
37,2223,2,Clark County,2091,--,"Perkins, Dr Claude G ES",Perkins C ES,RG,3700 Shadow Tree St,N Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
38,2223,2,Clark County,2092,--,Innovations Int'l Charter ES,Innovations ES,DCH,1600 E Oakey Blvd,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
39,2223,2,Clark County,2093,--,100 Academy of Engineering and Technology ES,100 Academy SET ES,DCH,2341 Comstock Dr,N Las Vegas,...,N,Y,KG,05,KG,05,--,--,--,--
40,2223,2,Clark County,2094,--,"Dickens, D L Dusty ES",Dickens ES,RG,5550 Milan Peak St,N Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
41,2223,2,Clark County,2095,--,"Bailey, Sister Robert Joseph ES",Bailey ES,RG,4525 Jimmy Durante Blvd,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
42,2223,2,Clark County,2096,--,"Roundy, Dr C Owen ES",Roundy ES,RG,2755 Mohawk St,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
43,2223,2,Clark County,2097,--,"Forbuss, Robert L ES",Forbuss ES,RG,8601 S Grand Canyon Dr,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
44,2223,2,Clark County,2098,--,"Steele, Judith D ES",Steele ES,RG,6995 W Eldorado Ln,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
45,2223,2,Clark County,2099,--,"Schorr, Steve ES",Schorr ES,RG,11420 Placid Street,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
46,2223,2,Clark County,2100,--,"Ward, Kitty McDonough ES",Ward Kitty ES,RG,5555 Horse Drive,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
47,2223,2,Clark County,2101,--,Blue Diamond ES,Blue Diamond ES,RG,6 Diamond St,Blue Diamond,...,N,Y,PK,05,KG,05,--,--,--,--
48,2223,2,Clark County,2102,--,Goodsprings ES,Goodsprings ES,RG,385 W San Pedro Ave,Goodsprings,...,N,Y,PK,05,KG,05,--,--,--,--
49,2223,2,Clark County,2103,--,"Lundy, Earl B ES",Lundy ES,RG,4405 Yellow Pine Ave,Mt Charleston,...,N,N,PK,05,KG,05,--,--,--,--

In [21]:
# Drop all rows where District != Clark County

# Define a condition
condition = School_List['District Name'] == 'Clark County'

# # Use the `drop()` function to drop rows that don't meet the condition
School_List = School_List.drop(School_List.index[~condition])

# # Print the resulting DataFrame
print(School_List)

     SchoolYear  District Code District Name  School Code ACT Code  \
7          2223              2  Clark County         2060       --
8          2223              2  Clark County         2061       --
9          2223              2  Clark County         2062       --
10         2223              2  Clark County         2064       --
11         2223              2  Clark County         2065       --
..          ...            ...           ...          ...      ...
386        2223              2  Clark County         2955   290214
387        2223              2  Clark County         2956   976280
388        2223              2  Clark County         2957   976274
389        2223              2  Clark County         2960       --
390        2223              2  Clark County         2965   290245

                      School Name School Abbreviation School Type  \
7             Thompson, Tyrone ES       Thompson T ES          RG
8             Abston, Sandra B ES           Abston ES          RG
9              Jenkins, Earl N ES          Jenkins ES          RG
10       Ellis, Robert & Sandy ES            Ellis ES          RG
11             Ortwein, Dennis ES          Ortwein ES          RG
..                            ...                 ...         ...
386                Desert Rose HS     Desert Rose ALT          AL
387  High Desert State Prison YOP          HGHDSRTYOP          CO
388           Mission High School          Mission HS          AL
389                    Child Find    Clark Child Find          SE
390                 Quest Program       Quest Program          RG

                 Mailing Address    Mailing City  ... Virtual Title I  \
7        10250 S. El Capitan Way       Las Vegas  ...       N       N
8            9950 W Tompkins Ave       Las Vegas  ...       N       Y
9           6950 Vegas Valley Dr       Las Vegas  ...       N       Y
10           3200 Artella Avenue       Henderson  ...       N       N
11       10926 Dean Martin Drive       Las Vegas  ...       N       Y
..                           ...             ...  ...     ...     ...
386             444 W Brooks Ave    N  Las Vegas  ...       N       Y
387          22010 Cold Creek Rd  Indian Springs  ...       N       N
388  801 Veterans Memorial Drive       Las Vegas  ...       N       Y
389          3626 S Pecos-McLeod       Las Vegas  ...       N       N
390      601 N Pecos Rd Suite 70       Las Vegas  ...       N       N

    Low Grade High Grade Acct Low Grade Level 1 Acct High Grade Level 1  \
7          PK         05                     KG                      05
8          PK         05                     KG                      05
9          PK         05                     KG                      05
10         PK         05                     KG                      05
11         PK         05                     KG                      05
..        ...        ...                    ...                     ...
386        09         12                     --                      --
387        09         12                     --                      --
388        06         12                     --                      --
389        PK         12                     KG                      05
390        KG         12                     01                      05

    Acct Low Grade Level 2 Acct High Grade Level 2 Acct Low Grade Level 3  \
7                       --                      --                     --
8                       --                      --                     --
9                       --                      --                     --
10                      --                      --                     --
11                      --                      --                     --
..                     ...                     ...                    ...
386                     --                      --                     09
387                     --                      --                     09
388                     06                      08                     09
389                     06                      08                     09
390                     06                      08                     09

    Acct High Grade Level 3
7                        --
8                        --
9                        --
10                       --
11                       --
..                      ...
386                      12
387                      12
388                      12
389                      12
390                      12

[384 rows x 38 columns]

In [22]:
School_List.head()

,SchoolYear,District Code,District Name,School Code,ACT Code,School Name,School Abbreviation,School Type,Mailing Address,Mailing City,...,Virtual,Title I,Low Grade,High Grade,Acct Low Grade Level 1,Acct High Grade Level 1,Acct Low Grade Level 2,Acct High Grade Level 2,Acct Low Grade Level 3,Acct High Grade Level 3
7,2223,2,Clark County,2060,--,"Thompson, Tyrone ES",Thompson T ES,RG,10250 S. El Capitan Way,Las Vegas,...,N,N,PK,05,KG,05,--,--,--,--
8,2223,2,Clark County,2061,--,"Abston, Sandra B ES",Abston ES,RG,9950 W Tompkins Ave,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
9,2223,2,Clark County,2062,--,"Jenkins, Earl N ES",Jenkins ES,RG,6950 Vegas Valley Dr,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--
10,2223,2,Clark County,2064,--,"Ellis, Robert & Sandy ES",Ellis ES,RG,3200 Artella Avenue,Henderson,...,N,N,PK,05,KG,05,--,--,--,--
11,2223,2,Clark County,2065,--,"Ortwein, Dennis ES",Ortwein ES,RG,10926 Dean Martin Drive,Las Vegas,...,N,Y,PK,05,KG,05,--,--,--,--

In [23]:
School_List.info()

<class 'pandas.core.frame.DataFrame'>
Index: 384 entries, 7 to 390
Data columns (total 38 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   SchoolYear               384 non-null    int64
 1   District Code            384 non-null    int64
 2   District Name            384 non-null    object
 3   School Code              384 non-null    int64
 4   ACT Code                 384 non-null    object
 5   School Name              384 non-null    object
 6   School Abbreviation      384 non-null    object
 7   School Type              384 non-null    object
 8   Mailing Address          384 non-null    object
 9   Mailing City             384 non-null    object
 10  Mailing State            384 non-null    object
 11  Mailing Zip              384 non-null    object
 12  Physical Address         384 non-null    object
 13  Physical City            384 non-null    object
 14  Physical State           384 non-null    object
 15  Physical Zip             384 non-null    object
 16  Principal Name           384 non-null    object
 17  Principal Email          384 non-null    object
 18  School Phone             384 non-null    object
 19  School Fax               384 non-null    object
 20  NCES District Code       384 non-null    object
 21  NCES School Code         384 non-null    object
 22  School Level             384 non-null    object
 23  Provision II             384 non-null    object
 24  CEP                      384 non-null    object
 25  ZOOM                     384 non-null    object
 26  Victory                  384 non-null    object
 27  APF                      384 non-null    object
 28  Virtual                  384 non-null    object
 29  Title I                  384 non-null    object
 30  Low Grade                384 non-null    object
 31  High Grade               384 non-null    object
 32  Acct Low Grade Level 1   384 non-null    object
 33  Acct High Grade Level 1  384 non-null    object
 34  Acct Low Grade Level 2   384 non-null    object
 35  Acct High Grade Level 2  384 non-null    object
 36  Acct Low Grade Level 3   384 non-null    object
 37  Acct High Grade Level 3  384 non-null    object
dtypes: int64(3), object(35)
memory usage: 117.0+ KB

In [24]:
School_List.to_csv("School_List_check.csv", index = False)

In [25]:
ELA_Math_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group                       385 non-null    object
 1   Organization Code           385 non-null    int64
 2   Mathematics - % Proficient  385 non-null    object
 3   ELA - % Proficient          385 non-null    object
dtypes: int64(1), object(3)
memory usage: 12.2+ KB

In [26]:
# join ELA_Math_all with School_List on ELA_Math_all ['Organization Code'] = School_List ['School Code']
# new dataframe = School_Perf_with_Address

School_Perf_with_Address = pd.merge(ELA_Math_all, School_List, 
                                    how='inner', 
                                    left_on='Organization Code', 
                                    right_on='School Code')

In [27]:
School_Perf_with_Address

,Group,Organization Code,Mathematics - % Proficient,ELA - % Proficient,SchoolYear,District Code,District Name,School Code,ACT Code,School Name,...,Virtual,Title I,Low Grade,High Grade,Acct Low Grade Level 1,Acct High Grade Level 1,Acct Low Grade Level 2,Acct High Grade Level 2,Acct Low Grade Level 3,Acct High Grade Level 3
0,100 Academy of Excellence,2364,-,23.5,2223,2,Clark County,2364,--,100 Academy of Engineering and Technology MS,...,N,Y,06,08,06,08,06,08,--,--
1,100 Academy of Excellence ES,2093,9.9,17.7,2223,2,Clark County,2093,--,100 Academy of Engineering and Technology ES,...,N,Y,KG,05,KG,05,--,--,--,--
2,"Abston, Sandra B ES",2061,40.3,47.0,2223,2,Clark County,2061,--,"Abston, Sandra B ES",...,N,Y,PK,05,KG,05,--,--,--,--
3,Addeliar D. Guy III Elementary School,2161,22.9,28.4,2223,2,Clark County,2161,--,"Guy, Addeliar D III ES",...,N,Y,PK,05,KG,05,--,--,--,--
4,Aggie Roberts Elementary School,2150,16.1,25.8,2223,2,Clark County,2150,--,"Roberts, Aggie ES",...,N,Y,PK,05,KG,05,--,--,--,--
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,Valley HS International Baccalaureate and Acad...,2404,7.0,22.0,2223,2,Clark County,2404,290102,Valley HS,...,N,Y,09,12,--,--,--,--,09,12
379,Veterans Tribute Career and Technical Academy,2432,28.5,67.6,2223,2,Clark County,2432,290215,Veterans Tribute CTA HS,...,N,N,09,12,--,--,--,--,09,12
380,Virgin Valley High School,2603,19.9,41.5,2223,2,Clark County,2603,290025,Virgin Valley HS,...,N,N,09,12,--,--,--,--,09,12
381,West Career and Technical Academy,2435,57.5,89.6,2223,2,Clark County,2435,290244,West Career & Technical Academy HS,...,N,N,09,12,--,--,--,--,09,12
382,Western High School,2405,<5,14.9,2223,2,Clark County,2405,290104,Western HS,...,N,Y,09,12,--,--,--,--,09,12

In [28]:
School_Perf_with_Address.columns

Index(['Group', 'Organization Code', 'Mathematics - % Proficient',
       'ELA - % Proficient', 'SchoolYear', 'District Code', 'District Name',
       'School Code', 'ACT Code', 'School Name', 'School Abbreviation',
       'School Type', 'Mailing Address', 'Mailing City', 'Mailing State',
       'Mailing Zip', 'Physical Address', 'Physical City', 'Physical State',
       'Physical Zip', 'Principal Name', 'Principal Email', 'School Phone',
       'School Fax', 'NCES District Code', 'NCES School Code', 'School Level',
       'Provision II', 'CEP', 'ZOOM', 'Victory', 'APF', 'Virtual', 'Title I',
       'Low Grade', 'High Grade', 'Acct Low Grade Level 1',
       'Acct High Grade Level 1', 'Acct Low Grade Level 2',
       'Acct High Grade Level 2', 'Acct Low Grade Level 3',
       'Acct High Grade Level 3'],
      dtype='object')

In [29]:
# Keep only relevant columns

School_Perf_with_Address = School_Perf_with_Address[['School Code', 'School Name', 'Mathematics - % Proficient','ELA - % Proficient', 'Physical Zip']]

In [30]:
School_Perf_with_Address.head()

,School Code,School Name,Mathematics - % Proficient,ELA - % Proficient,Physical Zip
0,2364,100 Academy of Engineering and Technology MS,-,23.5,89032
1,2093,100 Academy of Engineering and Technology ES,9.9,17.7,89032
2,2061,"Abston, Sandra B ES",40.3,47.0,89147
3,2161,"Guy, Addeliar D III ES",22.9,28.4,89031
4,2150,"Roberts, Aggie ES",16.1,25.8,89074

In [31]:
School_Perf_with_Zip = School_Perf_with_Address

In [32]:
School_Perf_with_Zip.head()

,School Code,School Name,Mathematics - % Proficient,ELA - % Proficient,Physical Zip
0,2364,100 Academy of Engineering and Technology MS,-,23.5,89032
1,2093,100 Academy of Engineering and Technology ES,9.9,17.7,89032
2,2061,"Abston, Sandra B ES",40.3,47.0,89147
3,2161,"Guy, Addeliar D III ES",22.9,28.4,89031
4,2150,"Roberts, Aggie ES",16.1,25.8,89074